version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: map_my_world_api
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/mapmyworld
    volumes:
      - .:/app

  db:
    image: postgres:13
    container_name: map_my_world_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mapmyworld
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
