"""Add unique constrains

Revision ID: 82b4eddf0b78
Revises: 8e9c48f88385
Create Date: 2024-11-11 01:41:52.302201

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "82b4eddf0b78"
down_revision = "8e9c48f88385"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("uix_category_name", "categories", ["name"])
    op.create_unique_constraint(
        "uix_location_lat_long", "locations", ["latitude", "longitude"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uix_location_lat_long", "locations", type_="unique")
    op.drop_constraint("uix_category_name", "categories", type_="unique")
    # ### end Alembic commands ###
